version:
  name: velociraptor
  version: 0.72.0
  commit: 7e4da7a
  build_time: "2024-04-25T16:09:17Z"
  install_time: 1716814933
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/8835780218
  compiler: go1.22.2
Client:
  server_urls:
  - https://logger:9000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQFTEh+YUeZIuMEe+PuhWB6TANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwNTI3MTMwMjMxWhcNMzQw
    NTI1MTMwMjMxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK6MMNVsPvP/ARltJJSTQugirf+YqnQF7K
    x5RzXtkpHiD/tMuKowiYnYdSu2/5xNn+p+dXQ6+IR9hdv3pgJ8Yobvdhr9R5ImD3
    93NmPTVuQRqQjCE6ksusQa1bgxS+Cl+ymXzRkc8+9YPd7ZA+SS6hMd+Z0OBBeHg9
    d1wu+2oINIzlCNIbbtGsf4+D/svjREq2qppkZM6jfjNyY9zRUquXNMweApQElbvJ
    bp1rN8S7P896P/1LxyEvRIMZEK4PLphdHihMYA1rnzt/bU5/AukrCds9CHFS53Xz
    KOPZytxxN4Hg/7eVy+mRzGbDwU0qNkDfeadc2cDysRQuY6Mp+l/lAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSIAzP++MgUi+CCTKUbgjOTraTw
    TzAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEARvBfyuV4Ds89jmPaF1mrYsGGkfZW92VXCvKvKHYeD3s4
    W/0mjOvTtIgLtUZOhy8eilBdz+E9utN7+ZwAVM2E+t5ZQykQsrI5Zoz8FWhrRQ2A
    iNQsjdYZsUGLHwSfjadacNhPHuHmaEKNR9v32vjfWa8eeXNLbIP337071GvOq/kq
    Sh3QGsoRKUvvV1eNLIDGWC7Mf5xxPxMppDuTy43syQD3lbpd1yW5ff7fLKhqwxuu
    oZNgEEYkiZmasMtTxbg6IKhfXOPPViDzSK6/LDu7p2aKCoU5fVzeB6VREmpH+MbR
    6mLfK8ptvtchPp4GXFCJw0Oshp1Y3ucA10ptkyM7SA==
    -----END CERTIFICATE-----
  nonce: VVDobpIqvZk=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.72.0
    commit: 7e4da7a
    build_time: "2024-04-25T16:09:17Z"
    install_time: 1716814933
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/8835780218
    compiler: go1.22.2
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
