version:
  name: velociraptor
  version: 0.72.0
  commit: 7e4da7a
  build_time: "2024-04-25T16:09:17Z"
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/8835780218
  compiler: go1.22.2
Client:
  server_urls:
  - https://logger:9000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQFTEh+YUeZIuMEe+PuhWB6TANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwNTI3MTMwMjMxWhcNMzQw
    NTI1MTMwMjMxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK6MMNVsPvP/ARltJJSTQugirf+YqnQF7K
    x5RzXtkpHiD/tMuKowiYnYdSu2/5xNn+p+dXQ6+IR9hdv3pgJ8Yobvdhr9R5ImD3
    93NmPTVuQRqQjCE6ksusQa1bgxS+Cl+ymXzRkc8+9YPd7ZA+SS6hMd+Z0OBBeHg9
    d1wu+2oINIzlCNIbbtGsf4+D/svjREq2qppkZM6jfjNyY9zRUquXNMweApQElbvJ
    bp1rN8S7P896P/1LxyEvRIMZEK4PLphdHihMYA1rnzt/bU5/AukrCds9CHFS53Xz
    KOPZytxxN4Hg/7eVy+mRzGbDwU0qNkDfeadc2cDysRQuY6Mp+l/lAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSIAzP++MgUi+CCTKUbgjOTraTw
    TzAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEARvBfyuV4Ds89jmPaF1mrYsGGkfZW92VXCvKvKHYeD3s4
    W/0mjOvTtIgLtUZOhy8eilBdz+E9utN7+ZwAVM2E+t5ZQykQsrI5Zoz8FWhrRQ2A
    iNQsjdYZsUGLHwSfjadacNhPHuHmaEKNR9v32vjfWa8eeXNLbIP337071GvOq/kq
    Sh3QGsoRKUvvV1eNLIDGWC7Mf5xxPxMppDuTy43syQD3lbpd1yW5ff7fLKhqwxuu
    oZNgEEYkiZmasMtTxbg6IKhfXOPPViDzSK6/LDu7p2aKCoU5fVzeB6VREmpH+MbR
    6mLfK8ptvtchPp4GXFCJw0Oshp1Y3ucA10ptkyM7SA==
    -----END CERTIFICATE-----
  nonce: VVDobpIqvZk=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.72.0
    commit: 7e4da7a
    build_time: "2024-04-25T16:09:17Z"
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/8835780218
    compiler: go1.22.2
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
API:
  hostname: logger
  bind_address: 192.168.56.105
  bind_port: 8001
  bind_scheme: tcp
  pinned_gw_name: GRPC_GW
GUI:
  bind_address: 192.168.56.105
  bind_port: 9999
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDQjCCAiqgAwIBAgIRAIa1M/12kSYiubCgR2J95PEwDQYJKoZIhvcNAQELBQAw
    GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MDUyNzEzMDIzMloXDTI1
    MDUyNzEzMDIzMlowKTEVMBMGA1UEChMMVmVsb2NpcmFwdG9yMRAwDgYDVQQDDAdH
    UlBDX0dXMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0QTp1Kg6FMEN
    RPkg20LvN8THAoAOSxH4LXuCvp74by/GQp6A/c3TLAhJJ7ZXk1BaRK0SXebix29Z
    fgS5NKIiypKEANBJs7g1/RJKmVyodjeWNvEZFp6Yp+/rucnvanrE/BjfmdkAd+gs
    ZWDywbZYr4A+lZWvC9TNXkxeQamsia+ZjFdDapXdu+sAE0I01o7J98DIOkBTibti
    LocvuY6c6ZxlD2FaZ4XR2wWUpjlS1GsbLTCP3rwaU/N//y1/x8bRRozItGo8p2iw
    JuB0h+YQ6EsykFoJQ7b8l/hLJdh+WyKfFTk4in7esTawXittciWuob5kDZNhUydj
    ijTG9WveWQIDAQABo3QwcjAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
    BQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUiAMz/vjI
    FIvggkylG4Izk62k8E8wEgYDVR0RBAswCYIHR1JQQ19HVzANBgkqhkiG9w0BAQsF
    AAOCAQEAAJeeD+wN2IAaNUhv3u5SuiqTfUcZhM6bsqi4EAOPVjd8/jXMtU5gT02z
    tBC4cABjPeuUkAcTr0zAWGgiJcreQfjYZmt18eCyFgvc5jv+1TvP2MDzcmDhvryp
    yEHejxBRkS8ARWTAtixb48LE7okS4Bhmz4I+T18JSW6+PjUCkMVnrnstBPCW1een
    6haxC82qM3vlr4ezM/Fpcymb3g2g9xaTYUL/aZ/Ys/afiLPZP1o9feIB5P0reahi
    ad71aZbYiUAMWklUfn/3iMOtLgk9zF96/AosIsLPgCMfZ3n5/glaszn/Xr+1ykHd
    1cw27GRYGthDW9kaId6H7rvo7bSm9A==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA0QTp1Kg6FMENRPkg20LvN8THAoAOSxH4LXuCvp74by/GQp6A
    /c3TLAhJJ7ZXk1BaRK0SXebix29ZfgS5NKIiypKEANBJs7g1/RJKmVyodjeWNvEZ
    Fp6Yp+/rucnvanrE/BjfmdkAd+gsZWDywbZYr4A+lZWvC9TNXkxeQamsia+ZjFdD
    apXdu+sAE0I01o7J98DIOkBTibtiLocvuY6c6ZxlD2FaZ4XR2wWUpjlS1GsbLTCP
    3rwaU/N//y1/x8bRRozItGo8p2iwJuB0h+YQ6EsykFoJQ7b8l/hLJdh+WyKfFTk4
    in7esTawXittciWuob5kDZNhUydjijTG9WveWQIDAQABAoIBABTzYiC/r/qukw7r
    zcBMiD/VyIDWpxgdN/wPGj7THmG+rye0TYejHtyWBAcn/sU0U6f4lRO2ddq5rYW1
    IX9GFSiq4PJX7ltGRpsUP0f6AqS+0560MeiTgweqQ71+oTHSFnaSY68/Eg3yxqhu
    vEZwaZlFyIAj3cTY0rD2BKieQj4WnlanbwEcX3UMaMoHQXIHNTwy7LR5Ei+G55/u
    QnwP/V0qdlLHfzlOUcN8QIjlFHVSGicFuy28ByrjpOFRLjCHFaMQxNsis6pyC57U
    Gl9qFDdgv0GxIolg3NkWq0b0PQgvJg01mcxhFP3PyE/2Imw8059JHPa4UnYbNSMB
    w8qmR5ECgYEA+Hk2U0FGeLGgkwCiVlSK+nsmCSwKxuOM2il45FFrDIHDdYa1MD/E
    E9W3ioyHGdhL1/OgeVi5Ipaw7w7L3HSWLOATFrg4zXEzN3KqPXn3cH/KmWeahVpS
    TLl8e+Ymjd09Vxp/5FA+5YxKUSTX5HT/OwVOxsWVqvmjCWxrlKxjagUCgYEA11nA
    u3OS8rjYwRO2w/8gA+MDivmQNYacnkdPl/jbw1Wnnk8elUtG8TJ4tjquO9pj8yx5
    IFN1T+8IgiunYE5sxJWdR11JcsCbGufl410ae7gBI30k1K2snlWFCAtMTcWOXef0
    GMwzXwS0A+LVGTSsjlc74+ctGAh4at2Q0DfiD0UCgYEAvztS4zqeyS80PU9EoZrJ
    p8P13yNFXBMviYxXnalH8UVBsIcvleXNu9JFQ12qcOq2XIsFm778JbHClQpXPeGA
    3yLJrje0h/EykN8wRMZE+RFxVSWWmEGOi7xKIXVdgNugZRRhD8/uyG5zmAX6Hrso
    4DzSh0r0SLV+lDcciT0v+h0CgYEAlLLX31fVnx4+JUv8hmey7pwhhSQADMWvfadV
    8WUYMlAB1tFhF8uL595m9cWdK50IKRCLbuPR/GjcYi3MfDaK6k84898ZaVBPiYuY
    9J8EO2t59cxi0yw9JnN80WojvQvt2y/gIANYcYLo3koRxT7W686Wfy7Qt2iZ5Yiq
    huwff1UCgYEAwUfbUPtgLC1YRbtlEXCGRgSGCkgsnwkrSU2ss47hxU0EO/ByQr6S
    QwWOyRDRRbNQkupJOKxHu1yCTprC5Q7YdA19GO47hjPyGZ+2IVV+Ynk40dDcWd/c
    igDglCrjLxicap6ZJzItJU8bNLQT7u929DRmTJZcjPB5Mpw8ZeGD3bA=
    -----END RSA PRIVATE KEY-----
  public_url: https://192.168.56.105:9999/
  links:
  - text: Documentation
    url: https://docs.velociraptor.app/
    icon_url: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MyIgaGVpZ2h0PSI2MyIgdmVyc2lvbj0iMS4xIiB2aWV3Qm94PSIwIDAgNTMgNjMiPjxwYXRoIGQ9Ik0yNyAzYy0zIDItMTMgOC0yMyAxMGw2IDMyYTEwMyAxMDMgMCAwIDAgMTcgMTZsNi01IDExLTExIDYtMzJDMzkgMTEgMzAgNSAyNyAzeiIgZmlsbD0iI2ZmZiIgZmlsbC1ydWxlPSJldmVub2RkIi8+PHBhdGggZD0iTTI2IDBDMjMgMiAxMiA4IDAgMTBjMSA3IDUgMzIgNyAzNWExMTMgMTEzIDAgMCAwIDE5IDE4bDctNiAxMi0xMmMyLTMgNi0yOCA4LTM1QzQwIDggMjkgMiAyNiAwWm0wIDU1LTYtNC04LTktNS0yNnYtMWwyLTFjOC0xIDE2LTYgMTYtNmwxLTEgMSAxczggNSAxNyA2bDEgMXYxcy0zIDIzLTUgMjZsLTggOWMtMiAyLTQgNC02IDR6IiBmaWxsPSIjYWIwMDAwIiBmaWxsLW9wYWNpdHk9IjEiIGZpbGwtcnVsZT0iZXZlbm9kZCIvPjxwYXRoIGQ9Ik0zOSAxOWExMzQ3IDEzNDcgMCAwIDEtMTMgMjZoLTJMMTQgMTloM2wyIDEgMSAxdjFhMjUwIDI1MCAwIDAgMSA2IDE3IDUyODkgNTI4OSAwIDAgMCA5LTIwaDR6IiBmaWxsPSIjMDAwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9ImJ1dHQiIHN0cm9rZS1saW5lam9pbj0ibWl0ZXIiIHN0cm9rZS13aWR0aD0iMSIvPjwvc3ZnPg==
    type: sidebar
    new_tab: true
  initial_users:
  - name: admin
    password_hash: 1f31ce15aca22c9dc637ab3530c18626a35c9a9b3cfd6eca3812461297a838f6
    password_salt: 7be24afd631952a89ca7fc3ec72f9170fbd9becc3d9cf3672feaf43e0b965f38
  authenticator:
    type: Basic
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAyujDDVbD7z/wEZbSSUk0LoIq3/mKp0BeyseUc17ZKR4g/7TL
    iqMImJ2HUrtv+cTZ/qfnV0OviEfYXb96YCfGKG73Ya/UeSJg9/dzZj01bkEakIwh
    OpLLrEGtW4MUvgpfspl80ZHPPvWD3e2QPkkuoTHfmdDgQXh4PXdcLvtqCDSM5QjS
    G27RrH+Pg/7L40RKtqqaZGTOo34zcmPc0VKrlzTMHgKUBJW7yW6dazfEuz/Pej/9
    S8chL0SDGRCuDy6YXR4oTGANa587f21OfwLpKwnbPQhxUud18yjj2crccTeB4P+3
    lcvpkcxmw8FNKjZA33mnXNnA8rEULmOjKfpf5QIDAQABAoIBAQC7PJw4o9b74Bks
    cessGzPestjTgtbSTRDrt80hxOVJDvdOXkvwa08UXVCxJCtI5MBwQAm2ucuxSvK6
    V2WaczlkuDjo2LKM8Q9f4eSH9HVofwT/W3+SKEFve893gXbTgokaKo5GaHFAXJfJ
    Y11WTHuN3ZLCwj8dywfRWGIlLHSEiiu8vk9GZKwnQAYTmwoewNzX+eNjI8xMJ3JA
    KIL6tyFb8EyhHeYYr1PWjAB3v0StJAleVsvDSFkTVidfaicHm7EeLXfMBG7mWEYG
    SC1+TfiZiTg1HeM0twAgrVPHMCK/AtMRMdBLqlJE/kUXaadKx2nUf342+gWSNKoL
    IjckXnWFAoGBAPT2MW0OReN2/j4W4CVnojkh6QofaXNBdH+iW4Wx438Ih8IwCvWL
    WI5bZ82USiiWsIjL3Tbec7ONzeMRVe40n3lkQgANBbe6ptlyXf4lheVDTocXORoq
    fu5/6vM7Njxmg7tKXnClw1LoF6AH9jqzyYLvCJyEBqnYz7YaH/1g5uMfAoGBANQN
    dr0yBbzsNz61dJN37vHIRT85wTeLl3TRBi5LBcj+RZP9+7hV79kk3If0BP8OpEDi
    aR2uNPxyK2uNuTk+o/ZDLdLGF9uNk3v1tXl+aG8e0YyzgpeN5KEAup35MQyIXpZg
    fiCMovAlb0r+3mBluen8TkSqZx35itLnAaoMzMB7AoGBAKuiYEk4KfHRqxwX7R9o
    OHrtbpogHkOaRiUzvgqz9GFKucxu2w7mfrroAphBYaCEzNZcePf773eMUQjbWakY
    h/CHNdNRTINKLaPIBWGQKvvTKA9xTxotUliLmjSodTzm2z/8QKWPD4dkhUEksvq4
    g+XQ0+jOfNi+x/Kg5W8kWUIjAoGAFgcwBodjwTRoqMMA0TDsSYGcb+z3/WUq3p+4
    HKb+etqvL6h6tbN3rv79ScI3oqdKuNLMSKEIMBFMIWgfjarMLZDc+cBKSixy3bWw
    nGZdQu3Ypt0e+89pqLACstZoGf0wlj5/27HAW2IIJapEP49RuNTU7J0nCR4bJb2J
    lritrHECgYAw9IFa5kfo8F0FCzRhsKnfZ7GgpnSFKdTvYwtFcKbMMy8slbXT51QD
    yXpy7rP+iZSVucUDL2IkG+uQMNFJPbEsiLcC3hDy4VXfkwxqBgAf8IVT1YDbgpGo
    7aBUhMZCK5Fzkv9YM0HXNp/nGe6w+VkIITg+3l1BsZj/CYlxttCiXw==
    -----END RSA PRIVATE KEY-----
Frontend:
  hostname: 192.168.56.105
  bind_address: 0.0.0.0
  bind_port: 9000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDVzCCAj+gAwIBAgIQBUshWHamDH3wl4REhIPLkjANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwNTI3MTMwMjMyWhcNMjUw
    NTI3MTMwMjMyWjA0MRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZl
    bG9jaXJhcHRvclNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
    AM43PsS9T0RUeHOOqZ5ASKPmzZFNQnwmd7U7bsqFhCCcoYqlIz6UKSv8BMvNhKl1
    XxnE9LU4cPiARFaWC60ANZszxP/Xeqh2y3WvrDN+Gac/2PlgdrJ9gl+cVEz9ZEMk
    uKw6bHKifybYvlpNXlTvXSrx28ehHt4vHNip5G3nAFD/D8UXdZALpZfJzgAcrH4H
    MMQTWRbM509Ad7VFYqb4NsclKvXquuj6/9yIuiJMOnlaa5Mqmy+slOB+sRe5oq2G
    aDoawL5IPSdDAMRpI2I6SyN+VSnZ7cPOzFarLAWa2J4lSI5/vK3WPIkbopm59VQU
    HIgRQ8hn2PcwrZ0e8ueYLhUCAwEAAaN/MH0wDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
    MBaAFIgDM/74yBSL4IJMpRuCM5OtpPBPMB0GA1UdEQQWMBSCElZlbG9jaXJhcHRv
    clNlcnZlcjANBgkqhkiG9w0BAQsFAAOCAQEALIfYcboESqPomlhhFVv5iZmm0tT1
    nMblj1uGDkmA3YiFuL0/mpQxocZazuBUzivyYmaCYfKSN5x3U45XGxRCQrV82ftf
    2Bq4yzlXiXSIeafCuFMNhC5A+GNUQ1nqsrKacolEuSFS0hQ0mighRG0PJ5VN4hNo
    yE7bpxyLbUuq6v60wIE4KfZicBmS7HEb+f5EZn8tv0pfmNr3UDzVNfGzsLEKzTlL
    zh6Tb9sQVDlw1Bd0Mxd4GabmG27s3b69966nzzVhA/Awk7XxGl15HaYRMslzXtKt
    re/fazGbLddBGeiYXhM+ELCygbWIoTvsWyG0gDjX0h2exZOXeAk7CmemLQ==
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAzjc+xL1PRFR4c46pnkBIo+bNkU1CfCZ3tTtuyoWEIJyhiqUj
    PpQpK/wEy82EqXVfGcT0tThw+IBEVpYLrQA1mzPE/9d6qHbLda+sM34Zpz/Y+WB2
    sn2CX5xUTP1kQyS4rDpscqJ/Jti+Wk1eVO9dKvHbx6Ee3i8c2KnkbecAUP8PxRd1
    kAull8nOABysfgcwxBNZFsznT0B3tUVipvg2xyUq9eq66Pr/3Ii6Ikw6eVprkyqb
    L6yU4H6xF7mirYZoOhrAvkg9J0MAxGkjYjpLI35VKdntw87MVqssBZrYniVIjn+8
    rdY8iRuimbn1VBQciBFDyGfY9zCtnR7y55guFQIDAQABAoIBABVn8LEVgavzJMnC
    DmNqAuBYrhAeN/+RMq3ybG7Da1LDT5WHzN/LG3cAYzMQs2uvzl5rbod9Q2TYU7+1
    NaMQuX/R4Oo54Pap1jbyNGrn9RvCafCBDfE7TBRGsw2G5CiAIFdofSdtLMvIhgHz
    tA4XBtHVZ14SoJSpyVHIWPj7mLHPiIuDhmYBckrmnHAdHwz+SwvdoHIwHW2OJd3v
    7eMf+GfkSrKEBt1ZdvehtF1VmCviQopw+bPKyuFaap/t5q6P6T5BJXo/jagrrtcx
    tvNRaZ8cz+xMtZWzoNZ+bekKbgITHA74L+FO5Qnq1/RGHGHgH6sQA7VHtR20kczh
    HhpHY+UCgYEA4j3oOEywIS8j6TbhwLVO8XVc6p7d4rWT0tPdo3JDhVKpHa6KGpgi
    j5Cb+pfVEm57JGzf0CXWPkJvGErdMfWKBKiqsDq5C5eMPTnSMLGzVmTtq/z/NMNY
    AOo0ZPgkgDyENLoZ3H4f6d0cUfpEM3GV/3qDHPPmTfEpyCNcp0KHCkMCgYEA6VcD
    0SshGoDsXOANAXRzwiSA6MZCWKQ6FMCsp6Wthf89TLsjnOo2/fi8d+28c+Mxhao+
    JNVcnbvHHxcfs1hE8qIEo789dryOf7LCEStDmYvJB6k8pDbeombidfD2lockcLx+
    TbXCpxWEfnPOY9jD0oAAXmYyDXkJljWAGqwyvMcCgYAtfflF6NW5tnroGCsIzuxS
    zSCj5NIFFjHlQMjeZsmA84AiAcivVEwOxis3FnS3whNs3Z+bgSA1YLJqFhOoShE4
    opm/2e7/j7eZUBkdxX2kL6NC5BqFB4qYlH94lhTw3DpRR+KPXaUZJ2bcbRBtr7dT
    qdTXa4uxvH6ESegFkfEJdQKBgQCJz1xvwtswPgha6fCEdXSQquJ/l+hDVer/qrPN
    56nOQ+q+UKA94o5L/QXChuQQRZRP7zX4pxKmDesST6PnVjCSZGH9G8t/PumiPb8k
    SLsKCmbWYXtxOP7QR5dkNMZOLM62znyCBOFLsQepb1fr3G/6+KI/HnhdQKkKz9oy
    5pSorQKBgCljxzWBHj3oNdS+H69n+T6v1E4nYQkkTWewLTxGvEdtDz+8okmCwr1N
    i3+aZdr7auAxZRhh1H5y0xPrf4gAFlXxKe+VXOq6XwEYHQxAGUN/sNMcLIBLcAlQ
    FrosnTJHDOPZmG9NWjhzTnQi4YAVlAzEoP2m+2LZ6Q2FSt/zEasS
    -----END RSA PRIVATE KEY-----
  dyn_dns: {}
  default_client_monitoring_artifacts:
  - Generic.Client.Stats
  run_as_user: velociraptor
  GRPC_pool_max_size: 100
  GRPC_pool_max_wait: 60
  resources:
    connections_per_second: 100
    notifications_per_second: 30
    max_upload_size: 10485760
    expected_clients: 30000
Datastore:
  implementation: FileBaseDataStore
  location: /opt/velociraptor
  filestore_directory: /opt/velociraptor
Logging:
  output_directory: /opt/velociraptor/logs
  separate_logs_per_component: true
  debug:
    disabled: true
  info:
    rotation_time: 604800
    max_age: 31536000
  error:
    rotation_time: 604800
    max_age: 31536000
Monitoring:
  bind_address: 192.168.56.105
  bind_port: 8003
api_config: {}
server_type: linux
obfuscation_nonce: noKyUe3MEwg=
defaults:
  hunt_expiry_hours: 168
  notebook_cell_timeout_min: 10
  notebook_number_of_local_workers: 5
